# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/pylothub
    docker:
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1
        environment:
          PIPENV_VENV_IN_PROJECT: true

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages

      - restore_cache:
<<<<<<< HEAD
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
=======
          key:
          - deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
>>>>>>> 27d37149311fc6936a6a8c271a09bbe2903f6807

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install
            pipenv install -dev

      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
        
      - run:
          name: run tests
          command: |
            pipenv run "python manage.py test"

      - store_artifacts:
          path: test-reports/
          destination: test-reports
          