# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/pylothub
    docker:
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.1-browsers
        environment:
          PIPENV_VENV_IN_PROJECT: true
          CC_TEST_REPORTER_ID: 9644d6a5115b63951aa8e98f4a12242f3346f36d84dc061c535105bfbec89546

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages

      - restore_cache:
          keys:
            - deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install
            pipenv install -dev

      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
        
      - run:
          name: initialize db
          command: |
            pipenv run python manage.py makemigrations
            pipenv run python manage.py migrate

      - run:
          name: run tests
          command: |
            pipenv run coverage run manage.py test
            ./cc-test-reporter before-build
            pipenv run coverage xml
            ./cc-test-reporter after-build -t coverage.py --exit-code $?

      - store_artifacts:
          path: test-reports/
          destination: test-reports
          
